# These are supported funding model platforms

github: https://github.com/latiefahmad
ko_fi: https://ko-fi.com/latiefahmad
buy_me_a_coffee: https://buymeacoffee.com/latiefahmad
custom: [https://saweria.co/latiefahmad, https://trakteer.id/latiefahmad/tip]
